### ISSUE TITLE
Post an array of device events to the webserver

### ISSUE THREAD

**Issue by bertdemiranda** [jyates/manning-energy-resources#5]
(...)
    // Modified code
    // -------------
    // then we convert them to an array of events that 
    // can be converted to e.g. an ArrayList<...>
     String message = "[" + events.stream().map(event -> {
     try {
        return MAPPER.writeValueAsString(event);
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    }).collect(Collectors.joining(",\n")) + "]";
    (...)

**Comment by jyates** [comment]
Thanks for the suggestion! It looks like you are trying to convert the events into a 'proper' JSON list. In that case, it would make more sense to just serialize the list directly via the ObjectMapper.

However, what im trying to simulate here is more of a 'streaming' approach to sending the events, where the device is dumping each event on the buffer and then can just periodically flush that buffer without any extra modifications. Since the body of each message is guaranteed to not have a newline character, this is a quite simple approach. It also is much easier to read on the server-side as you can interpret the event BLOB as just reading a series of lines.

If we wanted to get fancy here, we could do something like encoding the length of each event before the event. Instead, I'm optimizing for ease of understanding just looking at the payload, while still giving some of the "feel"of IoT constraints.

**Comment by bertdemiranda** [comment]
Thanks for your reply!
It would be just as easy to initialise a buffer with "[", and then add records separated with ",(newline)".
Just before POSTing the buffer add a closing "]".
In this way less coding is needed at the server side; Jersey/Jackson will do the work!
